### ISSUE TITLE
Can you support any jabber servers?

### ISSUE THREAD

**Issue by orloffv** [appleboy/drone-gtalk#5]
Not only gtalk

**Comment by orloffv** [comment]
<img width="493" alt="screen shot 2016-11-02 at 18 44 40" src="https://cloud.githubusercontent.com/assets/504986/19935817/76069baa-a12c-11e6-91c8-704b892e8ac6.png">
If add this params to config does work?

**Comment by appleboy** [comment]
@orloffv OK. I will make `Host` as configurable.

**Comment by orloffv** [comment]
In our configuration we configure login server and host:
Login server: our-company.com
Host: xmpp.our-company.com

**Comment by appleboy** [comment]
OK I will take it.

New Variable: `TLS_HOST` and `XMPP_HOST`

Is it OK?

**Comment by orloffv** [comment]
Cool!
